// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

import Foundation

/// Centralized definitions for translation keys that require special handling.
///
/// Some translation keys need to be excluded from localization (e.g., bundle identifiers)
/// while others are required to have translations (e.g., privacy permission strings).
enum L10nTranslationKeys {
    // MARK: - Excluded Translations

    /// Base translation keys that should never be localized.
    /// These are system-level identifiers that must remain in English.
    static let baseExcluded: Set<String> = [
        "CFBundleName",
        "CFBundleDisplayName",
        "CFBundleShortVersionString"
    ]

    /// Additional keys excluded only during export.
    /// These are third-party strings that shouldn't be sent for translation.
    static let exportOnlyExcluded: Set<String> = [
        "1Password Fill Browser Action"
    ]

    /// All excluded keys for import operations.
    static let excludedForImport: Set<String> = baseExcluded

    /// All excluded keys for export operations.
    static let excludedForExport: Set<String> = baseExcluded.union(exportOnlyExcluded)

    // MARK: - Required Translations

    /// Base translation keys that must have a target value.
    /// If missing, the source text is used as fallback.
    /// Required for: privacy permission strings (app crashes without them).
    static let baseRequired: Set<String> = [
        // Client/Info.plist
        "NSCameraUsageDescription",
        "NSLocationWhenInUseUsageDescription",
        "NSMicrophoneUsageDescription",
        "NSPhotoLibraryAddUsageDescription",
        "ShortcutItemTitleNewPrivateTab",
        "ShortcutItemTitleNewTab",
        "ShortcutItemTitleQRCode"
    ]

    /// WidgetKit translation keys (App Store requirement for Firefox).
    /// These cryptic IDs are generated by Xcode for widget intents.
    static let widgetKit: Set<String> = [
        "2GqvPe",
        "ctDNmu",
        "eHmH1H",
        "eqyNJg",
        "eV8mOT",
        "fi3W24-2GqvPe",
        "fi3W24-eHmH1H",
        "fi3W24-scEmjs",
        "fi3W24-xRJbBP",
        "PzSrmZ-2GqvPe",
        "PzSrmZ-eHmH1H",
        "PzSrmZ-scEmjs",
        "PzSrmZ-xRJbBP",
        "scEmjs",
        "w9jdPK",
        "xRJbBP"
    ]

    /// Returns the set of required translations based on configuration.
    /// - Parameter includeWidgetKit: Whether to include WidgetKit keys
    /// - Returns: Set of translation keys that must have target values
    static func required(includeWidgetKit: Bool) -> Set<String> {
        if includeWidgetKit {
            return baseRequired.union(widgetKit)
        }
        return baseRequired
    }
}
